component_depth: 2
languages:
- typescript
exclude:
- /Deploymentscripts/
- /Smartcontracts/
- /App/src/node_modules/
- /App/www/
- /App/src/smartcontracts/smartcontracts.ts
- /App/src/providers/contract-provider/contract-provider.ts
- /App/src/components/components-menu-bar/components-menu-bar.ts
- /App/src/app/app.component.ts
- /App/src/mocks/
- /Gates/src/node_modules/
- /Gates/www/
